<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="A2v10.Platform" Version="10.1.8665" />
		<PackageReference Include="A2v10.Web.Assets" Version="10.1.8665" />
		<PackageReference Include="A2v10.ReportEngine.Pdf" Version="10.1.8665" />
		<PackageReference Include="A2v10.Metadata" Version="10.1.8665" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MainApp\MainApp.csproj" />
	</ItemGroup>
</Project>
